name: Oppdater valutakurser

on:
  schedule:
    - cron: '2 * * * *'  # 2 min over hver hele time (UTC)
  workflow_dispatch:

jobs:
  fetch-valuta:
    runs-on: ubuntu-latest

    steps:
    - name: Sjekk ut repo
      uses: actions/checkout@v3

    - name: Hent valutakurser fra Open Exchange Rates
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        curl "https://openexchangerates.org/api/latest.json?app_id=$API_KEY&symbols=AED,AFN,ALL,AMD,AOA,ARS,AUD,AWG,AZN,BAM,BBD,BDT,BGN,BHD,BIF,BMD,BND,BOB,BRL,BSD,BTC,BTN,BWP,BYN,BZD,CAD,CDF,CHF,CLF,CLP,CNH,CNY,COP,CRC,CUC,CUP,CVE,CZK,DJF,DKK,DOP,DZD,EGP,ERN,ETB,EUR,FJD,FKP,GBP,GEL,GGP,GHS,GIP,GMD,GNF,GTQ,GYD,HKD,HNL,HRK,HTG,HUF,IDR,ILS,IMP,INR,IQD,IRR,ISK,JEP,JMD,JOD,JPY,KES,KGS,KHR,KMF,KPW,KRW,KWD,KYD,KZT,LAK,LBP,LKR,LRD,LSL,LYD,MAD,MDL,MGA,MKD,MMK,MNT,MOP,MRU,MUR,MVR,MWK,MXN,MYR,MZN,NAD,NGN,NIO,NOK,NPR,NZD,OMR,PAB,PEN,PGK,PHP,PKR,PLN,PYG,QAR,RON,RSD,RUB,RWF,SAR,SBD,SCR,SDG,SEK,SGD,SHP,SLE,SOS,SRD,SSP,STN,SVC,SYP,SZL,THB,TJS,TMT,TND,TOP,TRY,TTD,TWD,TZS,UAH,UGX,USD,UYU,UZS,VES,VND,VUV,WST,XAF,XAG,XAU,XCD,XCG,XDR,XOF,XPD,XPF,XPT,YER,ZAR,ZMW,ZWG" -o data/currency_rates.json
   
    - name: Commit og push ny fil
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add data/currency_rates.json
        git commit -m "Oppdater valutakurser automatisk"
        git push https://x-access-token:${GH_TOKEN}@github.com/RegnskApp/regnskapp.github.io.git
